import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Impact framework ecosystem",
    description: "Generated by Abdul Samad",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>if-ecosystem</title>
            </head>
            <link rel="icon" href="/favicon.svg" sizes="any" />
            <body className={inter.className}>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
